/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   checker_bonus.h                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sscheini <sscheini@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/03/17 16:35:49 by sscheini          #+#    #+#             */
/*   Updated: 2025/03/17 19:15:12 by sscheini         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef CHECKER_BONUS_H
# define CHECKER_BONUS_H
# include "libft/libft.h"

/*--------------------------------------------------------------------------*/
/*-------------------------------TROUBLESHOOT-------------------------------*/
/*--------------------------------------------------------------------------*/

/*	Verifies that the inputed values recieved as argument meet the			*/
/*	folowing requisites:													*/
/*	- Values inputed are integers numbers.									*/
/*	- Numbers inputed are betweeen the MAX_INT and MIN_INT, both included.	*/
/*	- Numbers inputed are unique and do not repeat.							*/
/*	If all the requisites are met returns an INT * array with the values.	*/
int		*ft_stack_check(char **argv, int *ptr_len);

/*	Frees a numeric T_LIST ** structure and the INT * array					*/
/*	used to create it.														*/
void	*ft_stack_free(int *ptr, t_list **stacks);							

/*	Frees a CHAR ** array generated by an ft_split execution.				*/
void	*ft_split_free(char **split);

/*	Push_swap failsafe.														*/
int		ft_forcend(int *ptr, t_list **stacks, char **order_arr);

/*--------------------------------------------------------------------------*/
/*-------------------------------INSTRUCTIONS-------------------------------*/
/*--------------------------------------------------------------------------*/

# define NO_ORDER -1

/* Pushes the first element from STACK B to STACK A as it's first.			*/
# define PA_ORDER 0

/* Pushes the first element from STACK A to STACK B as it's first.			*/
# define PB_ORDER 1

/* Swaps the first two elements of STACK A.									*/
# define SA_ORDER 2

/* Rotates every element on STACK A one position down, making the last		*/
/* element it's first.														*/
# define RRA_ORDER 3

/* Rotates every element on STACK A one position up, making the first		*/
/* element it's last.														*/
# define RA_ORDER 4

/* Swaps the first two elements of STACK B.									*/
# define SB_ORDER 5

/* Rotates every element on STACK B one position down, making the last		*/
/* element it's first.														*/
# define RRB_ORDER 6

/* Rotates every element on STACK B one position up, making the first		*/
/* element it's last.														*/
# define RB_ORDER 7

/* Swaps the first two elements of both STACKS.								*/
# define SS_ORDER 8

/* Rotates every element on both STACKS one position down, making the last	*/
/* elements their first.													*/
# define RRR_ORDER 9

/* Rotates every element on both STACKS one position up, making the first	*/
/* elements their last.														*/
# define RR_ORDER 10

/* Pushes the first element from stack_src to stack_des as it's first.		*/
/* - If executed correctly, returns 1. Else, returns 0.						*/
int		ft_push(t_list **stack_src, t_list **stack_des);

/* Rotates every element on the stack one position down, making the last	*/
/* element it's first.														*/
/* - If executed correctly, returns 1. Else, returns 0.						*/
int		ft_reverse_rotate(t_list **stack);

/* Rotates every element on the stack one position up, making the first		*/
/* element it's last.														*/
/* - If executed correctly, returns 1. Else, returns 0.						*/
int		ft_rotate(t_list **stack);

/* Swaps the first two elements of the stack passed as argument.			*/
/* - If executed correctly, returns 1. Else, returns 0.						*/
int		ft_swap(t_list **stack);

/* Executes the instruction sent as argument one time with both stack_a		*/
/* and stack_b.																*/
/* - If executed correctly, returns 1. Else, returns 0.						*/
int		ft_double(int (*ins)(t_list **), t_list **stack_a, t_list **stack_b);

/*	Executes a given instruction:											*/
/*	||	PA_ORDER	==	0													*/
/*	||	PB_ORDER	==	1													*/
/*	||	SA_ORDER	==	2													*/
/*	||	RA_ORDER	==	3													*/
/*	||	RRA_ORDER	==	4													*/
/*	||	SB_ORDER	==	5													*/
/*	||	RB_ORDER	==	6													*/
/*	||	RRB_ORDER	==	7													*/
/*	||	SS_ORDER	==	8													*/
/*	||	RR_ORDER	==	9													*/
/*	||	RRR_ORDER 	==	10													*/
/*	- If the instruction isn't valid, returns 0.							*/
int		ft_execute(int instruction, t_list **stacks);

/*	Checks if a numeric T_LIST * structure is sorted.						*/
/*	- Positive direction checks max to min sort.							*/
/*	- Negative direction checks min to max sort.							*/
/*	- Returns the amount of sort errors found on the stack, 0 equals sorted.*/
/*	- Notice that an empty list is a sorted one.							*/
int		ft_checksort_lst(t_list *stack, int dir);

#endif