/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   push_swap_troubleshoot.c                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sscheini <sscheini@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/01/09 20:10:26 by sscheini          #+#    #+#             */
/*   Updated: 2025/02/05 20:27:58 by sscheini         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "push_swap.h"

/* Frees the created stacks, which are a combination of an INT *ptr and a	*/
/* T_LIST **stacks.															*/
void	*ft_stack_free(int *ptr, t_list **stacks)
{
	t_list	*aux;

	if (ptr)
	{
		free(ptr);
		aux = stacks[0];
		while (aux)
		{
			aux->content = NULL;
			aux = aux->next;
		}
	}
	if (stacks)
	{
		ft_lstclear(stacks, free);
		free(stacks);
	}
	return (NULL);
}

/* Frees a CHAR ** array, usually generated by an ft_split() execution.		*/
void	*ft_split_free(char **split)
{
	int	i;

	i = -1;
	if (split)
	{
		while (split[++i])
			free(split[i]);
		free(split);
	}
	return (NULL);
}

/* Failsafe specific to push_swap in case of error.							*/
/* - Frees the stacks, which are a combination of an INT * ptr and a		*/
/*	 T_LIST ** stacks, and the CHAR ** order_arr.							*/
/* - Returns -1 to indicate an error ocurred.								*/
int	ft_forcend(int *ptr, t_list **stacks, char **order_arr)
{
	ft_stack_free(ptr, stacks);
	ft_split_free(order_arr);
	ft_printfd(2, "Error\n");
	return (-1);
}
